### ISSUE TITLE
sync batch timeouts

### ISSUE THREAD

**Issue by cruikshj** [Zywave/OctopusDeploy-Kraken#17]
the sync batch operation will timeout trying to sync to an environment with old deployments or syncing a large number of projects

we should optimize the Octopus api calls and bump up the timeout

**Comment by p-ob** [comment]
Closed with 1cf90e3401255d6bf77f126509ebd90683932a6b

**Comment by cruikshj** [comment]
should this be closed?

**Comment by p-ob** [comment]
Yes, this should have been closed when I posted that comment.
