### ISSUE TITLE
Create Appveyor NuGet feed for releases 

### ISSUE THREAD

**Issue by dpiessens** [Zywave/OctopusDeploy-Kraken#23]
Use the Appveyor NuGet feed to push releases in addition to GitHub so someone can add it to Octopus instead of downloading and then uploading packages.

**Comment by cruikshj** [comment]
Awesome idea.  I didn’t know you could hit the AppVeyor feed externally.

**Comment by dpiessens** [comment]
To be honest I'm not completely confident you can but I wanted to give it a try and see :)

**Comment by cruikshj** [comment]
This already works! I have updated the [Installation Guide](https://github.com/Zywave/OctopusDeploy-Kraken/wiki/Installation) to reflect this workflow.

Thanks for the idea.

**Comment by cruikshj** [comment]
Closed with AppVeyor already being magical.
