### ISSUE TITLE
cmdrjs does not work in IE without polyfill

### ISSUE THREAD

**Issue by dpiessens** [Zywave/OctopusDeploy-Kraken#24]
When using remote desktop or older browsers, the key binding to open cmdrjs doesn't work. (Client had IE 10 and was going through VisionApp). A button to open the console as a backup with be great and a little more intuitive to get started.

**Comment by cruikshj** [comment]
Are you using the latest kraken release?

The UI has a manage button to open cmdrjs.

Also, IE may not work at all with cmdrjs without the babel-polyfill.  I will add that to kraken.

**Comment by dpiessens** [comment]
I was using the 0.0.8 release, but maybe I just missed the button. The
polyfill may be a good add though :)

**Comment by cruikshj** [comment]
3531e38d84a28383f58272b6261eb68ac6c6ed7e
