### ISSUE TITLE
Show deployment progress for batches (including success/fail)

### ISSUE THREAD

**Issue by p-ob** [Zywave/OctopusDeploy-Kraken#26]
Currently, Kraken can only be used to queue up deployments; to check the success/failure of each deployment (or even the progress of the deployment) requires the user to go into Octopus and look at each project individually. It would be ideal if we could display some sort of per-environment message to show that a deployment is in progress, or that a deployment was successful or unsuccessful.

**Comment by p-ob** [comment]
@cruikshj I'm still leaving this issue open to go over it some more. Currently, because I'm using PROGRESS as a command, if the user is on details page the command takes control over cmdrjs (as it processes every 5 seconds). 

Octopus uses an interval between 5 and 6 seconds which is where I'm getting that number from.

**Comment by cruikshj** [comment]
That definitely wont work... passive ajax calls should not be commands
