### ISSUE TITLE
Improve logging for setup issues

### ISSUE THREAD

**Issue by dpiessens** [Zywave/OctopusDeploy-Kraken#36]
I've had a few clients setup Kraken and the one complaint is that the app always seems to start but gets this message if the DB or Octopus Link fails:

![kraken_error](https://cloud.githubusercontent.com/assets/64921/13827521/eb530a72-eb8a-11e5-8483-bf665acb188a.png)

It would be nice if more details could be shown or a log could be accessed to see the error in detail.

**Comment by cruikshj** [comment]
- Improved exception handling 9074d092056ea4fde33bf0f9fd8b1ca4d22c85a4
- Allow for logging to be enabled via octo variable 674b5a7797fd8df2f3a509e016f325fcbfab74d4

**Comment by cruikshj** [comment]
Octo variable to enable logging is **StdoutLogEnabled**

Log will write to the root deploy location in a logs folder.

**Comment by cruikshj** [comment]
documented at

https://github.com/Zywave/OctopusDeploy-Kraken/wiki/Troubleshooting
