### ISSUE TITLE
setup CI

### ISSUE THREAD

**Issue by cruikshj** [Zywave/OctopusDeploy-Kraken#5]
appveyor

**Comment by dpiessens** [comment]
Looks like this is the easiest way to set it up for appveyor: https://github.com/T4MVC/R4MVC/blob/master/build.cmd They don't have the Appveyor yml checked in but I would recommend that.

**Comment by cruikshj** [comment]
Ended up using the Visual Studio 2015 RC os... this comes with DNX so didnt need too complex of a script.
