### ISSUE TITLE
Don't show projects in LINKPROJ if already part of the batch

### ISSUE THREAD

**Issue by p-ob** [Zywave/OctopusDeploy-Kraken#55]
Currently, I can see a project to add to a batch, select it, and tell Kraken to add it. We are not allowing duplicate projects to be added to the batch in the controller, so why show the project at all?

**Comment by cruikshj** [comment]
the difficulty probably out weighs the benefit.  the autocomplete would have to be far smarter than it is now.  right now it is built generically.  it would have to be aware of the the other parameters for this to work.
