### ISSUE TITLE
Authentication changes in Octopus 3.5 likely will have broken Kraken Auth

### ISSUE THREAD

**Issue by cruikshj** [Zywave/OctopusDeploy-Kraken#63]
https://octopus.com/downloads/compare?from=3.4.15&to=3.5.1

We will need to rethink authentication, probably using Oauth.

**Comment by dpiessens** [comment]
Did you see if you could just put it straight into Octopus as a server
extension? Then you wouldn't need a separate login.

**Comment by cruikshj** [comment]
That is an interesting approach.  I was thinking of releasing Kraken 1.0 and then exploring that as a hosting option.

Is there a server extension library where I could register Kraken?

**Comment by dpiessens** [comment]
Yes, There's some rough documents out there for it:
http://docs.octopusdeploy.com/display/OD/Customising+an+Octopus+Deploy+server+extension


If you look at some of the example extensions it shows how to deliver UI
payloads and interact with the server. I haven't done much with it but it
would save deployment time :)
