### ISSUE TITLE
deploy with kraken

### ISSUE THREAD

**Issue by Kapilit** [Zywave/OctopusDeploy-Kraken#72]
hi,

Can we make kraken to do something like below

consider we have got two branches, one with version 1.0 and other with 2.0. i wan kraken to deploy 1.0 to test1 and 2.0 to test2

thanks
Kapil

**Comment by cruikshj** [comment]
Octopus Deploy can deploy any package version to any target.  I suggest creating two Octopus projects, one for each branch.

Remember, Kraken is just an extension of Octopus that does things in batches.  Octopus is still where individual projects are managed.
