### ISSUE TITLE
Octopus 3.11.5 Upgrade has broken Sync Functionality. GetBatchEnvironments - 500 Internal Server Error

### ISSUE THREAD

**Issue by JMacProdigy** [Zywave/OctopusDeploy-Kraken#76]
I have upgraded Kraken to .6 prerelease and this feature is still broken following the upgrade of Octopus Server. Sync no longer sees the Octopus Environments and only shows sync for latest nuget packages and latest releases.

      Executed action Kraken.Controllers.Api.ReleaseBatchesController.**GetBatchEnvironments** (Kraken) in 732.7436ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 733.321ms 500 text/plain; charset=utf-8

**Comment by JMacProdigy** [comment]
Manual sync via the console appears to work fine. UI Sync is the issue.

**Comment by p-ob** [comment]
I believe this will be fixed with this pull request: https://github.com/Zywave/OctopusDeploy-Kraken/pull/75

**Comment by JMacProdigy** [comment]
Is it possible for a new release including these changes? Thanks!

**Comment by p-ob** [comment]
We've published a new [prerelease](https://github.com/Zywave/OctopusDeploy-Kraken/releases/tag/1.1.0-prerelease.7) with the NuGet package update. Enjoy!

Note: This came with some other dependency updates, so you may need to update the [.NET Core Windows Server Hosting bundle](https://go.microsoft.com/fwlink/?linkid=844461). If you use Chocolatey, you can just update [this](https://chocolatey.org/packages/dotnetcore-windowshosting).
