### ISSUE TITLE
Deploying a batch does respect individual lifecycle settings

### ISSUE THREAD

**Issue by kirk-quinbar** [Zywave/OctopusDeploy-Kraken#83]
the scenario is I had multiple service deploys going to our US and UK servers. one of the services had a lifecycle set to not include the UK, but when i deployed the batch to the UK it still tried to deploy the one service i had lifecycle set to not include UK. 

I think batch deploys should always follow lifecycle settings at the project level before just deploying them.

**Comment by cruikshj** [comment]
Are you sure?  I tested this, and got the expected error in Kraken console.  I suspect your lifecycle is allowed to deploy to UK.
